[workspace]
members = ["core", "debugger", "zebes"]
default-members = ["zebes"]
resolver = "2"

[workspace.package]
version = "0.1.4"
edition = "2024"
authors = ["dnlzrgz <contact@dnlzrgz.com>"]
repository = "https://github.com/dnlzrgz/zebes"
license = "MIT"
readme = "README.md"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
